apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-nginx-app
  template:
    metadata:
      labels:
        app: my-nginx-app
    spec:
      containers:
      - name: my-nginx-app
        image: jakehazex21/my-nginx-app:latest  # Docker Hub image
        ports:
        - containerPort: 80
        - containerPort: 443
        imagePullPolicy: Always  # Always pull the latest image from DockerHub

