apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-ingress
  namespace: default  # Assuming the ingress is in the 'default' namespace
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
    argocd.argoproj.io/compare-options: IgnoreExtraneous
spec:
  rules:
  - host: beatsinthe.cloud
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: my-nginx-app
            port:
              number: 80
      - path: /blog
        pathType: Prefix
        backend:
          service:
            name: ghost-app-service
            namespace: default  # Explicitly reference the ghost namespace
            port:
              number: 80  # Port 80 if you're exposing Ghost via service at 80
  - host: www.beatsinthe.cloud
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: my-nginx-app
            port:
              number: 80
      - path: /blog
        pathType: Prefix
        backend:
          service:
            name: ghost-app-service
            namespace: default  # Explicitly reference the ghost namespace
            port:
              number: 80
  tls:
  - hosts:
    - beatsinthe.cloud
    - www.beatsinthe.cloud
    secretName: cloudfi-tls-secret
