apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
images:
  - name: jakehazex21/my-nginx-app
    newTag: 4e2fde9  # This will be replaced by the Image Updater
