apiVersion: v1
kind: Service
metadata:
  name: my-nginx-app
spec:
  selector:
    app: my-nginx-app
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
  type: ClusterIP

