apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: traefik-secret-reader
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: traefik-secret-reader-binding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: traefik-secret-reader
subjects:
  - kind: ServiceAccount
    name: traefik
    namespace: kube-system
