apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: self-managed-argocd
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  source:
    path: argo-cd 
    repoURL: https://github.com/catinahat85/CloudFiLive.git
    targetRevision: main 
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
