apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghost-app
  namespace: ghost
  labels:
    app: ghost-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ghost-app
  template:
    metadata:
      labels:
        app: ghost-app
    spec:
      containers:
      - name: ghost-app
        image: ghost:5.72.0
        ports:
        - containerPort: 2368
        env:
          - name: database__client
            value: mysql
          - name: database__connection__host
            value: your-mysql-host
          - name: database__connection__user
            value: your-mysql-user
          - name: database__connection__password
            valueFrom:
              secretKeyRef:
                name: ghost-app-secrets
                key: mysql-password
          - name: database__connection__database
            value: ghost
          - name: useNullAsDefault
            value: "true"
          - name: debug
            value: "false"
          - name: url
            value: http://5.78.119.50/ghost
        volumeMounts:
        - name: ghost-content
          mountPath: /var/lib/ghost/content
      volumes:
      - name: ghost-content
        persistentVolumeClaim:
          claimName: ghost-content-pvc  # Your PVC claim for content

