apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghost-app
  labels:
    app: ghost-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ghost-app
  template:
    metadata:
      labels:
        app: ghost-app
    spec:
      containers:
      - name: ghost-app
        image: ghost:5.72.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 2368
        volumeMounts:
        - name: ghost-content
          mountPath: /var/lib/ghost/content
        env:
        - name: database__client
          value: mysql
        - name: database__connection__host
          value: <your-mysql-host>
        - name: database__connection__user
          value: ghost
        - name: database__connection__password
          valueFrom:
            secretKeyRef:
              name: ghost-app-secrets
              key: mysql-password
        - name: database__connection__database
          value: ghost
        - name: useNullAsDefault
          value: "true"
        - name: url
          value: https://your-blog-url.com
        - name: mail__transport
          value: SMTP
        - name: mail__options__
