apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cloudfi-tls
  namespace: default
spec:
  secretName: cloudfi-tls-secret
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-production
  commonName: beatsinthe.cloud
  dnsNames:
    - beatsinthe.cloud
    - www.beatsinthe.cloud
