apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: example-com-tls
  namespace: default
spec:
  secretName: beatsinthecloud-com-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: beatsinthe.cloud
  dnsNames:
  - beatsinthe.cloud
  - www.beatsinthe.cloud
