apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cloudfi-tls
  namespace: default
spec:
  secretName: new-cloudfi-tls-secret
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: beatsinthe.cloud
  dnsNames:
  - beatsinthe.cloud
  - www.beatsinthe.cloud
