name: Build, Push Docker Image, and Deploy to Kubernetes

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: jakehazex21/my-nginx-app:latest

    - name: Set up Kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'v1.30.0'  # Or the version that matches your K8s cluster

    - name: Apply Kubeconfig
      run: |
        mkdir -p $HOME/.kube  # Create the .kube directory if it doesn't exist
        echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config  # Write Kubeconfig to the file
        kubectl config set-context --current --namespace=default  # Set your desired namespace if needed

    - name: Deploy to Kubernetes
      run: |
        echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config  # Use the Kubeconfig from secrets
        kubectl config set-context --current --namespace=default  

      env:
        KUBECONFIG: ${{ secrets.KUBECONFIG }}  # Your Kubernetes config for authentication
