name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Triggers when changes are pushed to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # This defines the environment for the build job

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  # Uses the secret for the Docker username
        password: ${{ secrets.DOCKER_PASSWORD }}  # Uses the secret for the Docker password

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: jakehazex21/my-nginx-app:latest
        context: .

    - name: Log out of Docker Hub
      run: docker logout
